### ISSUE TITLE
Duplicated CSS rules

### ISSUE THREAD

**Issue by cawa-93** [gambitph/Titan-Framework#271]
```php
		$titan = TitanFramework::getInstance( 'fpp' );
		$set = $titan->createAdminPanel( array(
			'name' => __('Default Like button', 'fpp'),
			'parent' => 'fpp-main'
		));
		$set->createOption( array(
			'name' => __('Background color', 'fpp'),
			'id' => 'background_color',
			'type' => 'color',
			'default' => '#0b0b0b',
		));
		$set->createOption( array(
			'name' => __('Background opacity', 'fpp'),
			'id' => 'background_opacity',
			'type' => 'number',
			'default' => '0.8',
			'min' => 0,
			'max' => 1,
			'step'=> 0.01
		));
		$titan->createCSS('
			.mfp-bg {
				background: $background_color !important;
				opacity: $background_opacity !important;
			}
		');
```
In the file titan-framework-fpp-css.css CSS rules are duplicated:
```CSS
.mfp-bg{background:#d33 !important;opacity:1 !important;}.mfp-bg{background:#d33 !important;opacity:1 !important;}
```
